# -----------------------------------------------------------------------------
# Run in background: 
#     docker-compose up -d
#
# Check status: 
#     docker-compose ps
#
# View logs of service ssh.pool-1.1.1: 
#     docker-compose logs ssh.pool-1.1.1
# -----------------------------------------------------------------------------
ssh.pool-1.1.1:
  image: "jdeathe/centos-ssh:centos-6"
  container_name: "ssh.pool-1.1.1"
  ports:
    - "2020:22"
